name: shopping
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  # Default
  cupertino_icons: ^1.0.2

  # State management

  # Cache
  shared_preferences: ^2.0.15

  auto_route:
    ^4.0.1

    # ui utilities
  flutter_native_splash: ^2.2.3+1
  auto_size_text: ^3.0.0

  # LOCALIZATION
  easy_localization: ^3.0.1

  # Network
  http: ^0.13.4
  provider: ^6.0.3

dev_dependencies:
  auto_route_generator: ^4.0.0
  build_runner: ^2.1.11

  flutter_test:
    sdk: flutter

  #LAUNCHER ICON
  flutter_launcher_icons: "^0.9.2"

  flutter_lints: ^2.0.0

flutter_native_splash:
  #color: "#323f5c""
  background_image: "assets/images/monkey_splash_screen.png"
  #image: "assets/icon/shopping_cart.png"
  #image: "assets/images/logo.png"
  android_12:

flutter_icons:
  android: "launcher_icon"
  #  ios: true
  image_path: "assets/icon/monke_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/images/
    - assets/images/onboard/
    - assets/translations/
