name: shopping
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.2.3+1
  cupertino_icons: ^1.0.2

  # LOCALIZATION
  easy_localization: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  #LAUNCHER ICON
  flutter_launcher_icons: "^0.9.2"

  flutter_lints: ^2.0.0

flutter_native_splash:
  #color: "#323f5c""
  background_image: "assets/images/monkey_splash_screen.png"
  #image: "assets/icon/shopping_cart.png"
  #image: "assets/images/logo.png"
  android_12:

flutter_icons:
  android: "launcher_icon"
  #  ios: true
  image_path: "assets/icon/monke_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/images/
    - assets/translations/
